pycontribs/jenkinsapi

jenkinsapi/job.py
When passing `skip_if_running=True` to `Job.invoke()` it prints a warning message (*Will not request new build because JOB_NAME is already running*) but then still triggers a build.
=> fix invoke(skip_if_running=True) triggering a build even when a build is already running

jenkinsapi/job.py
which doesn't have "parameterDefinitions" under "actions", but rather under "property"
=> Taking care of Workflow (official) plugin job

jenkinsapi/job.py, jenkinsapi_tests/systests/test_parameterized_builds.py
when no other non-file parameters are passed
Currently, the latest version of the library doesn't work with file parameters at all. Period. However, there is a way to do it - just use only file parameters with `buildWithParameters`. In my case, I need to pass a complex parameter structure, and it was easy to put everything into a json file and pass it to Jenkins for further parsing/analysis.
=> Allowing using standalone file parameter with buildWithParameters

jenkinsapi/job.py
Based on this thread https://github.com/salimfadhley/jenkinsapi/issues/369, this PR adds the option to return the full response object, if needed, from the update_config method.
I feel like there should be also a test for this method, but couldn't find any, I can try to work on one, though.
Thanks!
=> Return full response object, if requested, on job.update_config method.

doc/source/index.rst
This note would have been helpful on the front page.
=> Adding a note about using an API token as password

jenkinsapi/utils/krb_requester.py
The standard implementation of `Requester` passes an `allow_redirects` boolean parameter. There's no hook in `KrbRequester` for this parameter, but it seems both unnecessary and unadjustable. Assuming nothing changes in the execution, a simple `**kwargs` permits usage of KrbRequester. This is necessary for us to use the python jenkinsapi libs.
=> KrbRequester.get_request_dict missing **kwargs

jenkinsapi/api.py, jenkinsapi/jenkins.py
There are times when one doesn't want to verify the jenkins master certificate.
Although, this can be done by passing such a requester, ssl_verify argument
will do the job and make the code more readable.
=> Add ssl_verify flag to the Jenkins class

jenkinsapi/__init__.py, jenkinsapi/credential.py, jenkinsapi/credentials.py, jenkinsapi/custom_exceptions.py, jenkinsapi/jenkins.py, jenkinsapi/node.py, jenkinsapi/nodes.py, jenkinsapi_tests/systests/__init__.py, jenkinsapi_tests/systests/test_credentials.py, jenkinsapi_tests/systests/test_executors.py, jenkinsapi_tests/systests/test_nodes.py, jenkinsapi_tests/unittests/test_node.py
This change adds:
- Credentials class - for operations on Jenkins credentials
- UsernamePasswordCredential - to hold username and password credentials
- SSHKeyCredential - for ssh key credentials
- ability to create ssh slaves
JNLP slave creation was unified with SSH slaves, so both have similar way of making them.
=> Credentials and ssh nodes

jenkinsapi/build.py
Hey here is the patch for the issue #396 I created. Jenkins uses the ISO-8859-1 as an encoding so using it to decode the byte streams worked. Thanks.
=> Decoding bytes with the ISO-8859-1 encoding

jenkinsapi/__init__.py
Dear all, let me request simple change in jenkinsapi/__init__.py file to
allow developers and users to work with jenkinsapi without necessity of installing.
Current (master as of 2015-09-08 or last stable release) does very focused check whether jenkinsapi is used as part of unit testing (nosetests) which is typically not working in deployments where you checkout the code and adjust PYTHONPATH.
My suggestion here is to use bogus version when pkg_resources query fails.
=> FIX: allow jenkinsapi to be used without installation

jenkinsapi_tests/systests/job_configs.py
For some reason latest Jenkins versions format job's config.xml a bit different. This is to fix our formatting, so the test will pass.
=> Fixed EMPTY_JOB config to match the one returned from Jenkins

jenkinsapi/job.py
For jobs that are instances of CloudBees job templates of pipeline jobs, this has_params() indicates that there are no parameters, even though get_params_list() properly returns a list of parameters.
This was found while using Python 2.7
=> Can't find job parameters if in 'property'

setup.cfg
jenkinsapi already uploads wheel distributions. Since jenkinsapi is pure Python and supports both Python 2 and 3, it should use "universal wheels". Otherwise the wheel distribution will not be used on all supported platforms.
See: http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#universal-wheels
and http://pythonwheels.com/
=> Update setup.cfg to support universal wheels

jenkinsapi/node.py, jenkinsapi_tests/systests/test_nodes.py
Add function to node for querying the labels from the node's config.xml. The config.xml querying and caching was copied from the job's config handling code.
I tried running systests.test_nodes on windows but they all failed so I added the test speculatively. I tried my changes with a real jenkins setup and they work as expected.
=> Add jenkinsapi.Node.get_labels()

jenkinsapi_tests/systests/test_jenkins.py, jenkinsapi_tests/unittests/test_jenkins.py, jenkinsapi_utils/jenkins_launcher.py
I found that if I use `JENKINS_HOME` and 'JENKINS_URL' env variables to run tests, folder where JENKINS_HOME points to gets removed. Fixed that.
Moved some trivial unit tests to systests.
=> Proper handling of JENKINS_HOME variable and moving some unit tests into systests

examples/how_to/create_slave.py
Adding SSL disabling option using requester for Jenkins user behind https
Most jenkins users set authentication by deafult so I've added auth settings 
Java Heap setting should remove `=` 
Fixed `credential_descrip` to `credential_description` and added a comment that explains the importance of the the setting; if it's unset (or in my case using a wrong name) the node is configured as JNLP by mistake.
=> SSL, Authentication, JMX and some comments and fixes for create_slave.py exaple

.travis.yml, jenkinsapi/credentials.py, jenkinsapi/jenkins.py, jenkinsapi_utils/jenkins_launcher.py
Start Jenkins with `-Djenkins.install.runSetupWizard=false` parameter, which disables security and Setup wizard.
Fixes #448 - latest version of `credentials` plugin uses different url.
Made Travis test log verbose, so I don't have to wait till full test run to see which test is broken.
=> J2x insecure start

jenkinsapi/queue.py, jenkinsapi_tests/systests/test_queue.py
I'm currently using this library and noticed that it didn't have a way to read the "why" field of the QueueItem object without referring to _data directly.
This patch adds a property to make this cleaner. 
I didn't see any tests for this, so I haven't added any here. It's a pretty straightforward change.
=> Adding a why property to a queueitem object

examples/how_to/create_views.py, jenkinsapi/view.py, jenkinsapi/views.py
closes #467 
- adds support for [Categorized Jobs View plugin](https://wiki.jenkins-ci.org/display/JENKINS/Categorized+Jobs+View)
- change `View#add_job` to use the `addJobToView` action. This was needed because, even though I could add a Categorized Jobs View correctly, after adding jobs to it, it would have some configs erased.
I'm opening this PR so you can tell me whether this is good enough, or how should I improve. I'll write the tests as soon as you tell me the approach is correct.
I run the existing tests locally after the changes and they are all green. And I tested the new feature against my Jenkins instance and it works fine.
=> Categorized view plugin support and change View#add_job approach

jenkinsapi/artifact.py, jenkinsapi/utils/requester.py, jenkinsapi_tests/systests/job_configs.py, jenkinsapi_tests/systests/test_jenkins_artifacts.py
Made systest for artefact to be run with strict md5 check.
Artifact download now will not use `response.content`, but will use stream of binary chunks.
=> Strict artefact systest

jenkinsapi/build.py, jenkinsapi/job.py, jenkinsapi_tests/unittests/test_build.py, jenkinsapi_tests/unittests/test_job.py
Sometimes it's useful to have an ability of retrieving build by params the job was launched with. For example, if you want to fetch a last/first build for the specific params.
* Add 'get_params' for the build that allows to get dictionary with params
* Add 'get_build_by_params' to the job class that will compare build params with the specified one by one
* Add unittests
'get_build_by_params' method will make requests for each build, so it's network consuming call and makes sense only if you want to get first/last build by param (`order` keyword will help you) or have small amount of build ~20-30.
=> Add ability to retrieve build by params

jenkinsapi/credential.py, jenkinsapi/credentials.py, jenkinsapi_tests/systests/__init__.py, jenkinsapi_tests/systests/test_credentials.py, jenkinsapi_utils/jenkins_launcher.py
In order to do this, the plain-credentials plugin must be installed.
This requires an update of the bundled credentials plugin, so I
adapted the plugin installation to create an empty .pinned file for
each plugin.
Minor improvements: 
- set `jenkins_home` in JenkinsLauncher instance if `JENKINS_HOME` env var is defined
- `JenkinsLancher` -> `JenkinsLauncher`
- replace enumerate with regular for loop in the `install_plugin` method
=> Implement `Secret text` credential

.travis.yml, README.rst, jenkinsapi/build.py, jenkinsapi/job.py, jenkinsapi_tests/systests/get-jenkins-war.sh, jenkinsapi_tests/unittests/test_build.py, jenkinsapi_tests/unittests/test_job.py, requirements/dev-requirements.txt, setup.py
Fix for the issue when `parameters` in `actions` list is not the first element and we cannot rely on the order within this array. [Link to discussion](https://github.com/pycontribs/jenkinsapi/pull/488#discussion_r80270130)
* Separate test requirements into different file for easier development and updating related files
* Update `readme` with development instructions
* Remove `assert` statement from code as it should *only* be used within tests
* Check for `wget` executable presence as you can launch tests on machine without program installed
* Create additional unittests
Sorry for non-atomic pull request with changes in various places.
=> Fix 'get_build_by_params' method

jenkinsapi/build.py, jenkinsapi_tests/unittests/test_build.py
The artifacts returned in Build.get_artifacts all have their builds set to self. This causes an error retrieving fingerprint info when the artifact was actually generated by a different build. By retrieving the job and build numbers for artifacts associated with the job, we can ensure that
each artifact has accurate build information and can be properly validated on save.
This should resolve #458 although I can't be sure because my issue was slightly different.
=> Adds correct build information to Build.get_artifacts

jenkinsapi/artifact.py, jenkinsapi/build.py, jenkinsapi_tests/unittests/test_artifact.py
I found a bit of a bug in #511. If the original build no longer exists, you can't fetch it and error out when trying to get the build number. Instead, I looked more into why my builds failed validation. It turns out it's because I was saving them with a different filename than the one in Jenkins. I'm not sure why this only failed for artifacts from other builds, but the fix seems fairly straightforward. We should simply not validate the filename because there's no reason to do that. Instead, I validate the artifact's filename because we probably do want to make sure we're validating against the right object.
I also reverted #511 in this pull request, as it creates a worse bug than it was trying to fix.
As well as the added unit test, I tried this with my Jenkins and it allowed me to save …
=> Allow fn changes on save

jenkinsapi/build.py, jenkinsapi_tests/systests/conftest.py, jenkinsapi_tests/systests/job_configs.py, jenkinsapi_tests/systests/test_env_vars.py, jenkinsapi_tests/unittests/configs.py, jenkinsapi_tests/unittests/test_build.py
The build environment varialbes can be obtained from Jenkins thanks to the EnvInject plugin:
https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin
To support that in JenkinsAPI the get_env_vars method was added to the Build class.
closes #489
=> Add get_env_vars to Build

jenkinsapi/artifact.py, jenkinsapi/job.py, jenkinsapi/jobs.py, jenkinsapi_tests/unittests/test_jenkins.py
I recently ran in to the need to build and download the artifacts of a job in a folder. I ran in to the issues mentioned in #358 and #537.
This pull request allows for referencing jobs by their full path (`folder/job`). It keeps the old `job` references too to avoid breaking any existing scripts.
There may well be other places in the code with similar issues, but these were the ones I ran into first. I hope this helps people who have had similar problems.
=> Add support for jobs in folders.

jenkinsapi_tests/systests/test_crumbs_requester.py
Lately there were errors related to crumbs tests. They are due to changes in Jenkins: the json on securuty page now sends details of internal ssh server and Jenkins in unhappy if they are not present.
The change should not break Jenkins 1.x
=> fix crumbs related test for 2.x Jenkins

.travis.yml, jenkinsapi_tests/systests/test_crumbs_requester.py, jenkinsapi_utils/jenkins_launcher.py
The code should work with 1.x version, but may break in future.
Main reason for dropping 1.x is that for tests we use latest versions of plugins and they may be incompatible with old Jenkins. This could be handled by downloading specific versions of all plugins, but I have no time for such effort.
Thus release 0.3.4 was the last release which was tested with Jenkins 1.x
Instead of testing against Jenkins 1.x we will test against LTS (stable) and latest Jenkins versions.
This PR also changes how project is built in Travis - we need to use JDK8 (or, at least, guarantee that specific JDK version is in use).
=> Dropped support of Jenkins 1.x

jenkinsapi/credential.py
Ability to create AWS Credentials.
Example:
```
import jenkinsapi
from jenkinsapi.jenkins import Jenkins
from jenkinsapi.credential import AmazonWebServicesCredentials
J = Jenkins("http://localhost:8080", "username", "password")
creds = J.credentials
desc = "Test new credential"
new_aws_cred = {
"description": desc,
"accessKey": "MyAccessKey",
"secretKey": "MyAwesomeSecretKeyIsAwesome"
}
new_cred = AmazonWebServicesCredentials(new_aws_cred)
creds[desc] = new_cred
```
You need the [CloudBees AWS Credentials Plugin](https://wiki.jenkins.io/display/JENKINS/CloudBees+AWS+Credentials+Plugin)
=> Add support for AWS Credentials

jenkinsapi/build.py, jenkinsapi_tests/unittests/test_build.py, tox.ini
Also permit passing extra params to py.test (e.g. -k testname) for
faster iterations.
=> Close #583: Handle parameters with secret values

jenkinsapi/queue.py
It's possible for queued tasks to be unnamed. This is the case when using Pipeline jobs. Check that tasks have names before referring to it.
=> Fixes pycontribs/jenkinsapi#530.

README.rst
I came to your Github page to look for documentation and I just got the brief README summary with no idea your other docs existed until a co worker showed me.  I feel that this adds a lot of value to your README.
=> Add link to full docs in README

jenkinsapi/node.py, jenkinsapi_tests/unittests/test_node.py
These allow the querying of:
- The node's available and total physical memory.
- The node's available and total swap space.
- The local path of the node's workspace area.
- The size of the node's workspace area.
- The local path of the node's temporary area.
- The size of the node's temporary area.
- The node's architecture (eg. "Linux").
- The node's average response time.
- The clock difference between the node and the Jenkins master.
=> Added methods to Node for querying information stored in the monitors section of the api tree

jenkinsapi/jenkins.py, jenkinsapi/utils/requester.py
Add "cert" parameter to the Jenkins class init() that is passed down to requests library call arguments.
Reference:
http://docs.python-requests.org/en/master/api/
> cert -- (optional) if String, path to ssl client cert file (.pem). If Tuple, ('cert', 'key') pair.
=> Add support for client side certificates, closes #632

jenkinsapi/jenkins.py, jenkinsapi/utils/requester.py
The current krb_requester has a bug that spits out `TypeError`:
Sample code to reproduce
```
from jenkinsapi.utils.krb_requester import KrbRequester
import requests_kerberos
from jenkinsapi.jenkins import Jenkins
jenkins_url = <some_jenkins_url>
jobname = 'somejob'
requester = KrbRequester(baseurl=jenkins_url, mutual_auth=requests_kerberos.OPTIONAL)
myjenkins = Jenkins(jenkins_url, requester=requester)
job = myjenkins.get_job(jobname)
last_stable_build = job.get_last_stable_build()
print('last stable build slave is:')
print last_stable_build.get_slave()```
Error:
```Traceback (most recent call last):
File "krb_test.py", line 9, in <module>
requester = KrbRequester(baseurl='someurl', mutual_auth=requests_kerberos.OPTIONAL)
File "/Users/foobar/Library/Python/2.7/lib/python/site-packages/jenk …
```
=> Changing to  *args and **kwargs in requester init. Fixing TypeError bug

.travis.yml, jenkinsapi/credential.py, jenkinsapi_tests/systests/job_configs.py, jenkinsapi_tests/systests/test_credentials.py, jenkinsapi_tests/systests/test_crumbs_requester.py, jenkinsapi_tests/systests/test_jenkins_artifacts.py, jenkinsapi_tests/systests/test_nodes.py, pylintrc, test-requirements.txt, tox.ini
Refactored some tests and make sure that build runs on GCE - that's the only way to ensure that build runs w/o intemittent problems.
=> Remove ssh credentials no longer supported by ssh credentials plugin

README.rst
The development section of the README contained
information that was no longer up to date, making
contributions harder.
=> update README dev guide

jenkinsapi/jenkins.py, jenkinsapi/utils/requester.py, jenkinsapi_tests/unittests/test_jenkins.py, jenkinsapi_tests/unittests/test_requester.py
Hello,
This pull request adds a new function use_auth_cookie(). It is used like this:
```python
server = Jenkins(JENKINS_URL, username="user", password="password")
server.use_auth_cookie()
for job in server.get_jobs():
print(job)
```
This function will login and get the JSESSIONID cookie in jenkins and will use it every request from this moment on.
Doing that the performance skyrockets. Now the api is too slow because it has to authenticate in every request, and when we have to look for data in hundreds of jobs and builds, the times are just too high. This pull request fixes this issue.
I wrote the code trying to impact the rest of the api as least as possible.
BR.
=> Use session id cookie to improve performace

jenkinsapi/jenkins.py, jenkinsapi/queue.py
Since QueueItem has full job url, there is no need to find that job by name. We get `Job` object directly because we know that job exists.
=> Add new method to create job and use it to speedup QueueItem

jenkinsapi/jenkinsbase.py
example of URL, unparseable in current version: https://jenkins/job/shared/job/Shared%252FMaths/job/features%252Fdotnetjenkins/
=> url encode folder name, to fix forward slashes

jenkinsapi/build.py
* Artifact dictionary returned is indexed by relative_path
rather than a filename.
=> Fix for build.get_artifacts()

jenkinsapi_tests/systests/conftest.py, jenkinsapi_tests/systests/test_jenkins.py
Latest trilead-api refuses to run on LTS Jenkins - use last compatible version
Set all urls to jenkins.io - more stable
Use plugin w/o junit dependence for testing plugin installs. Junit
dependency (even implied to v1.0) causes instability in Jenkins.
Strip result string of groovy exec.
=> Fix failures caused by plugins

jenkinsapi/utils/requester.py, jenkinsapi_tests/unittests/test_requester.py
At least as of jenkins 2.176.3 csrf check requires the cookie
issued when requesting a csrf token to also be present in requests.
Prevents "Error 403 No valid crumb was included in the request"
=> Updates Requester to use a Session, maintaining cookies

jenkinsapi/jenkins.py, jenkinsapi/nodes.py
The current workflow in creating a new node allows the user to provide a small and limited array of configurations
```python
jenkins.create_node(name, num_executors=2, node_description=None,
remote_fs='/var/lib/jenkins',
labels=None, exclusive=False)
...
node_dict = {
'num_executors': num_executors,
'node_description': node_description,
'remote_fs': remote_fs,
'labels': labels,
'exclusive': exclusive
}
```
However, in order to configure the node to exactly how I would like it, I would have to create it, then send a modify step. 
This pull request allows an advanced user the ability to create the node exactly, right from the start. This is important because I have my configurations in source control so every new agent is created the same.
=> Create Node by providing predetermined configuration

jenkinsapi/node.py
=> don't fail when node_descriprion is missing

jenkinsapi/job.py
Jenkins has a [quiet period feature](https://jenkins.io/blog/2010/08/11/quiet-period-feature/) for waiting for a commit burst to be over before it triggers a new build. Jobs can set the quiet period in the configuration and we can override it by supplying a quiet period value in trigger url.
This pull request added the quiet period parameter to `Job.invoke`.
=> Add quiet period parameter to job invoke

jenkinsapi_tests/systests/conftest.py
It looks like `stable` version of Jenkins has a bug with plugins API call that was fixed in `latest` version. This causes all tests for `stable` Jenkins to fail.
=> Fixing plugin dependencies

jenkinsapi/job.py
Hi!
Currently, `update_config()` converts the `config` to `str` type without encoding format.
So it does not support unicode characters. For example:
```py
>>> jk.get_job('job1').update_config('中文') 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\Leo\AppData\Local\Programs\Python\Python39\lib\site-packages\jenkinsapi\job.py", line 640, in update_config
response = self.jenkins.requester.post_url(url, params={}, data=config)
...
File "C:\Users\Leo\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 164, in _encode
raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: Body ('中文') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```
So I submitted this PR …
=> Support for using unicode characters in update_config()

jenkinsapi/jenkins.py
This PR addresses the issue when Jenkins has a running job and /safeRestart is called.
Fixes: #844
=> fix: jenkinsapi crashing jenkins_is_unavaiable

README.rst
* Removed shell formatting from examples to allow users to directly copy
and paste
* Gave venv example a name and location
* Turned hyperlinks into proper links
* Remove requirements plugin, domain is for sale
=>  Readme Updates: Remove redundant words, move install and example to top

jenkinsapi_tests/unittests/test_build.py
pytest.warns(None) is an anti-pattern, and there are easier ways to accomplish both cases with how the code is leveraging pytest.warns(). Firstly, it can match on a specific warning and will assert that the warning is raised -- and it doesn't need to be used if we want to assert code raises no warnings, the standard library can do that directly. Furthermore, pytest.warns(None) is an error in Pytest 8 and above.
=> Do not make use of pytest.warns(None)

jenkinsapi/node.py
Add support for the `/computes/{node-name}/launchSlaveAgent` endpoint. For slaves that support launching (e.g. SSH slaves), this allows triggering a new try to connect the slave with jenkins. We need this, because setting a node online does not trigger a reconnect.
=> feature: add launch method to Node class
