- jenkinsapi/job.py
Need to check "parameterDefinitions" under "actions" and "property"
> Taking care of Workflow (official) plugin job in get_params.

- .gitignore
- jenkinsapi/jenkins.py
- jenkinsapi_tests/systests/test_restart.py
- jenkinsapi_tests/unittests/test_plugins.py
Just started working with the api and here are a few things I found missing.  Let me know if you like the look of these additions and if so I'll look into writing tests.
>  jenkins.install_plugin, jenkins.install_plugins, and jenkins.safe_restart

- examples/how_to/start_parameterized_build.py
Hi,
Just a very basic example of kicking off a parameterized build. One of the most basic use cases.
Thanks,
-Russ
> How to kick-off a parameterized build (eg build version, python version)

- jenkinsapi/build.py
- jenkinsapi_tests/unittests/test_build.py
Adding Changes to get jenkins build slave information
>  Add changes to get slave information

- doc/source/ssl_certificate_verification
As suggested [here](https://github.com/salimfadhley/jenkinsapi/pull/387#issuecomment-147850576) in #387, I have written a short description about that.
I know it's not good enough yet, but I would love to hear your feedback for making it more than perfect. :smiley: :godmode:
> Add a doc regarding ssl_verify arg in the Jenkins class

- jenkinsapi/build.py
This is a quick fix that allows to resolve issue #317
> Added get_changeset_items() method 

- README.rst
- examples/how_to/create_credentials.py
- examples/how_to/create_slave.py
- examples/how_to/delete_all_the_nodes_except_master.py
Added credentials and nodes examples
Removed crate.io badge
Reworded library capabilities list
> Doc changes

- jenkinsapi/credentials.py
- jenkinsapi/jenkins.py
REST API have been changed in latest version of Credentials plugin:
now it returns list of dicts instead of dict of dicts.
New Credentails2x class basically converts new structure to old one
> Fixes for Credentials 2.x plugin

- jenkinsapi/job.py
- jenkinsapi_tests/systests/test_parameterized_builds.py
- jenkinsapi_tests/unittests/test_job.py
I added a comment to the commit with the testing results.
> Make triggering parameterized builds also work with file parameters

- jenkinsapi/jenkins.py
- jenkinsapi/label.py
- jenkinsapi_tests/unittests/test_label.py
Initial version for supporting get tied jobs under specific label
> Add support for retrieve info for Label

- .travis.yml
- jenkinsapi/build.py
- jenkinsapi_utils/jenkins_launcher.py
Also reconfigured Travis to build with last 1.x release and latest 2.x
> Fix for broken build.stop() function with Jenkins 2.x

- jenkinsapi/job.py
- jenkinsapi_tests/systests/test_jenkins.py
This is to fix issue #462. Now properly encoding job search parameter.
Added test for that too.
> Fix job search

- .travis.yml
- jenkinsapi_tests/systests/__init__.py
- jenkinsapi_tests/systests/base.py
JUnit plugin now depends on another plugin.
> Fixed failing tests on Jenkins 2.0

- jenkinsapi/jenkins.py
- jenkinsapi/job.py
- jenkinsapi/jobs.py
> Restored old way of finding jobs

- jenkinsapi/view.py
- jenkinsapi_tests/systests/test_views.py
> Fixed get_config() for jobs returned from view

- jenkinsapi/utils/crumb_requester.py
> Added CrumbRequester

- jenkinsapi/job.py
> Added check for missing "firstBuild" item

- jenkinsapi/utils/crumb_requester.py
- jenkinsapi/utils/requester.py
- jenkinsapi_tests/systests/base.py
- jenkinsapi_tests/systests/test_crumbs_requester.py
> When job is invoked with file param http headers will be now set

- jenkinsapi/utils/crumb_requester.py
- setup.py
- tox.ini
This lets tox run successfully again
> fix up tox

- setup.py
The URL here is wrong since this is in pycontribs
> Fix source code url.

- jenkinsapi/build.py
> Add estimated duration accessor to build class

- .gitignore
- Makefile
- jenkinsapi/api.py
- jenkinsapi/build.py
- jenkinsapi/command_line/jenkins_invoke.py
- jenkinsapi/fingerprint.py
- jenkinsapi/jenkins.py
- jenkinsapi/job.py
- jenkinsapi/jobs.py
- jenkinsapi/utils/requester.py
- jenkinsapi/views.py
- pylintrc
- requirements/dev-requirements.txt
- setup.cfg
- tox.ini
Change-Id: I9121730c1ff0dc2ebea8b9ee833eac4a4c6e250e
> fix: linting

- jenkinsapi/utils/requester.py
Change-Id: If5a1bfa4cc405eeaf34c93992405edc64287ee51
> Enabled 5 retries at request lib level

- .travis.yml
- jenkinsapi_tests/systests/conftest.py
- jenkinsapi_tests/systests/test_restart.py
- jenkinsapi_utils/jenkins_launcher.py
Plus allowed building any and all branches in Travis, but set to release only from master
> Added missing plugin and changed wait for restart test

- jenkinsapi/credential.py
In the credential part, we need one more attribute when using the private key on master.
> Fix bug when using private key file(on master) to create ssh credential.

- jenkinsapi/jenkins.py
- jenkinsapi/utils/krb_requester.py
- jenkinsapi/utils/requester.py
> add timeout parameter to Jenkins object

- .travis.yml
- test-requirements.txt
- tox.ini
Codecov integration not working for a year, it is time to fix it.
> Fix Codecov integration

- jenkinsapi/jenkins.py
- jenkinsapi/plugin.py
- jenkinsapi/plugins.py
- jenkinsapi/utils/jsonp_to_json.py
- jenkinsapi/utils/manifest.py
- jenkinsapi_tests/systests/test_plugins.py
- jenkinsapi_tests/unittests/test_plugins.py
- pylintrc
This is PR#505 by @mvdbeek fixed and with pytest bases tests
> Plugin install improvements

- jenkinsapi/build.py
- jenkinsapi/jenkinsbase.py
- jenkinsapi/job.py
- jenkinsapi/nodes.py
- jenkinsapi/plugins.py
- jenkinsapi/utils/jsonp_to_json.py
- jenkinsapi/views.py
So pylint will be happier and tests will pass
> fix inconsistent return values

- jenkinsapi/job.py
- jenkinsapi_tests/systests/test_queue.py
> init QueueItem properly

- jenkinsapi/jenkins.py
- jenkinsapi/nodes.py
- do not loop over all nodes to get single node (suggested by #615)
- nodes url is calculated in Nodes
- proper exceptions raised from Nodes
- Jenkins won't do pre-check for existance of nodes
> Small Nodes refactoring

- jenkinsapi/queue.py
- jenkinsapi_tests/systests/test_queue.py
> add QueueItem.is_queued() and test for it

- jenkinsapi/nodes.py
- jenkinsapi_tests/unittests/test_nodes.py
Added new methods:
- Added Nodes.items()
- Added Nodes.itervalues()
- Added Nodes.values()
Added tests and docstrings for Nodes.keys(), Nodes.iterkeys() and Nodes.iternodes().
> Added more methods to Nodes to match the built-in dict methods

- jenkinsapi/jenkins.py
- jenkinsapi_tests/systests/test_jenkins.py
Add new method Jenkins.run_groovy_script(self, script) for running arbitrary groovy scripts on the Jenkins server. This fixes #601.
> Add new method for running groovy scripts on the Jenkins server

- jenkinsapi/build.py
- jenkinsapi_tests/unittests/test_build_scm_git.py
*Given a build get_repo_url shall return the git repo url of that build
* Implemented for git only as of now
> Retrieve git repo url for a given build

- jenkinsapi_utils/simple_post_logger.py
- test-requirements.txt
While trying to develop this project locally, I followed the instructions on the README. However, I kept running into issues with some `imports` that were either not installed or not found when developing locally.  
I added some changes with backwards compatibility to allow others to easily clone the repo and run `python setup.py test` and have it work.
> Fixed requirements and local imports

- .eggs/README.txt
- examples/how_to/use_crumbs.py
- jenkinsapi/build.py
- jenkinsapi_tests/unittests/configs.py
- jenkinsapi_tests/unittests/test_build.py
Sorry, not a Python expert, wasn't able to run all the tests, so the tests I touched haven't really been tested.
> Handle changesets returned by Jenkins job that use Pipeline

- jenkinsapi/build.py
- jenkinsapi/job.py
- jenkinsapi_tests/systests/test_invocation.py
two new methods in `Build` object:
`toggle_keep()` and `is_kept_forever()`
One new method in `Job` object: `toggle_keep_build()`
> add ability to keep build forever

- jenkinsapi/node.py
- jenkinsapi_tests/systests/test_nodes.py
Sometimes its useful to be able to update the offline reason on a node. This function does just that.
> Add method to update offline reason for a node.

- jenkinsapi/job.py
Please review this proposed fix for issue #692.
> Proposed CloudBees integration fix to job.invoke.

- jenkinsapi/job.py
- jenkinsapi_tests/systests/conftest.py
- jenkinsapi_tests/unittests/test_job_get_all_builds.py
> See if Jenkins is lazy when loading build history

- .gitignore
- setup.cfg
ignore of annoying dot files, regarding git and local testing
> ignore dot files

- jenkinsapi/jenkins.py
- jenkinsapi_tests/systests/test_generate_new_api_token.py
- setup.cfg
generates a new token for an existing and logged in user.
> generate new api token for logged in user

- examples/how_to/use_crumbs.py
- jenkinsapi/jenkins.py
- setup.cfg
Overly complicated to use crumb, having to duplicate requester parameters, this should make it easier for newcomers to utilize crumb while supporting backwards compatibility.
> simplify crumb usage

- jenkinsapi_tests/systests/conftest.py
- jenkinsapi_tests/systests/test_plugins.py
Test plugins functions with simpler plugins, the ones that don't depend on other plugins.
> Simple plugins

- jenkinsapi/node.py
I need to know when a node becomes idle again (waiting for jobs to finish) and the idle state was not being refreshed.
> Fixed idle state not being refreshed

- .gitignore
- examples/how_to/use_crumbs.py
- jenkinsapi/jenkins.py
Implements #755
https://travis-ci.com/pycontribs/jenkinsapi/builds/140992154
> useCrumbs -> use_crumbs

- jenkinsapi/jenkins.py
- jenkinsapi/jenkinsbase.py
- jenkinsapi/utils/requester.py
- jenkinsapi_tests/unittests/test_requester.py
This code did NOT have the expected impact: https://github.com/psf/requests/blob/v2.22.0/requests/adapters.py#L117
> Fixing retrying logic by introducing a max_retries param

- pyproject.toml
Resolves https://github.com/pycontribs/jenkinsapi/issues/835
> Fix console scripts in pyproject.toml

- jenkinsapi/build.py
> Decode content using the encoding specified in the response
